python3 dist_train.py --gpu_ids 0,1,2,3 \
        --dataset_mode    ProcessedVideo \
        --dataset_dirs    ./datasets/iPER ./datasets/MotionSynthetic ./datasets/fashionvideo \
        --output_dir      ./experiments \
        --model_id   uv_map_completion_2 \
        --image_size 512 \
        --num_source 5   \
        --time_step  1   \
        --batch_size 1   --Train.niters_or_epochs_no_decay 400000 \
        --gen_name uv_map_completion \
        --dis_name patch_global \
        --train_name UVmapTraniner \
        --master_port 13345
